logging:
  level:
    org: DEBUG

eureka:
  instance:
    # register via IP, instead of hostnames
    preferIpAddress: true
    #hostname: localhost
  client:
    #fetch registry when BE dependent service call is needed
    fetchRegistry: true
    # auto register with Eureka
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka


build:
  version: 2.0

accounts:
  message: "Welcome to Ts Bank's Account related dev back from real GIT APIs"
  contactDetails:
    name: Tushar Sood - Dev
    email: "{cipher}c87aebb3e8fd69a076aa3f1d6c0fae3973d1422353ddbe2a1cafa8632194f8eebab5a15c7bbc17c677d1856576e3dde3"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j:
  bulkhead:
    instances:
      getContactInfoV2:        
        maxConcurrentCalls: 5
  ratelimiter:
    configs:
      default:
        # maximum time to wait for new quota to arrive in case current quota has exahusted
        timeoutDuration: 1000
        limitRefreshPeriod: 5000
        limitForPeriod: 2
  retry:
    instances:
      getBuildInfo:
        baseConfig: default
    configs:
      default:
        maxAttempts: 5
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException
        retryExceptions:
          - java.util.concurrent.TimeoutException
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000


  
