server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

# these props would be available under actuator/info url
info:
  app:
    name: accounts
    description: TS Bank Accounts Application
    version: 1.0.0

spring:
  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  #datasource:
    # was not required on locallly but , needed when started inside a container
    # spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect -> can specify this up its optional
    #driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true  
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # this props is not required when using in mem DBs like H2
      # when using non in mem DBs, this rops specifies, that all classes annotated with entity should be created.
      # default value is none, which expects that, table should already exists.
      ddl-auto: update
    show-sql: true    
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    #   ddl-auto: create
    

build:
  version: 3.0

accounts:
  message: "Welcome to Ts Bank's Account related APIs"
  contactDetails:
    name: Tushar Sood - devloper
    email: ts@gmail.com
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235
