server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: cards
    version: 1.0.0

spring:
  h2:
    console:
      enabled: true  
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true