logging:
  level:
    org: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X${trace_id},%X{span_id}]"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # datasource:
  #   url: jdbc:h2:mem:testdb
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
    
eureka:
  instance:
    # register via IP, instead of hostnames
    preferIpAddress: true
  client:
    #fetch registry when BE dependent service call is needed
    fetchRegistry: true
    # auto register with Eureka
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

build:
  version: 2.0

cards:
  message: "Welcome to Ts Bank's Cards related dev back APIs"
  contactDetails:
    name: Tushar Sood - Dev
    email: ts-dev@gmail.com
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235
