server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: loans
    version: 1.0.0

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# spring:
#   h2:
#     console:
#       enabled: true
#   datasource:
#     url: jdbc:h2:mem:testdb
#   jpa:
#     properties:
#       hibernate:
#         format_sql: true
#     #   ddl-auto: create
#     show-sql: true