logging:
  level:
    org: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka


build:
  version: 2.0

accounts:
  message: "Welcome to Ts Bank's Loans related dev back APIs"
  contactDetails:
    name: Tushar Sood - Dev
    email: ts-dev@gmail.com
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
