server:
  port: 8072
logging:
  level:
    org: DEBUG


# set - management.info.env.enabled: true for adding custom props to actuator info    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  health:
    showDetails: always
  info:
    env:
      enabled: true

# this will be added to http://localhost:8072/actuator/info
info:
  app:
    name: "spring-cloud-gateway"
    version: 1.0.0

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
