server:
  port: 8072

# set - management.info.env.enabled: true for adding custom props to actuator info    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  health:
    showDetails: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# this will be added to http://localhost:8072/actuator/info
info:
  app:
    name: "spring-cloud-gateway"
    version: 1.0.0

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # this could be marked as false, we dont way gateway to create route using eureka registry
          enabled: true
          # enable smaller case service ids ot be linked to actual service route.
          lowerCaseServiceId: true
