logging:
  level:
    org: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X${trace_id},%X{span_id}]"

eureka:
  instance:
    preferIpAddress: true
  client:    
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

spring:
  cloud:
    gateway:
      httpclient:
        # mustr be specified in milliseconds
        connect-timeout: 8000
        # must be specified as a duration
        #response-timeout: 3s
        # incresed this latter to see effect to retry
        response-timeout: 16s
        
